# -*- coding: utf-8 -*-
"""BFSI Call Center AI Assistant .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgP45VXaJemnVc64XOdG36sUTpa3Rx_O
"""

# @title 1. Install All Required Packages
!pip install -q torch transformers datasets sentence-transformers chromadb peft accelerate bitsandbytes scikit-learn numpy pandas pyyaml gradio tqdm plotly
print("✅ All packages installed successfully!")

import os


dirs = [
    '/content/bfsi_assistant/data/knowledge_base',
    '/content/bfsi_assistant/src',
    '/content/bfsi_assistant/models',
    '/content/bfsi_assistant/data/embeddings',
    '/content/bfsi_assistant/logs'
]

for dir_path in dirs:
    os.makedirs(dir_path, exist_ok=True)

print("✅ Project folders created successfully!")
print("📍 Location: /content/bfsi_assistant/")

from google.colab import files
import json
import pandas as pd
from IPython.display import display, HTML

print("📤 Please upload your alpaca_dataset.json file")
print("="*50)

uploaded = files.upload()

for filename in uploaded.keys():
    if filename.endswith('.json'):

        filepath = f'/content/bfsi_assistant/data/{filename}'
        with open(filepath, 'wb') as f:
            f.write(uploaded[filename])


        with open(filepath, 'r', encoding='utf-8') as f:
            dataset = json.load(f)

        print(f"\n✅ Dataset loaded successfully!")
        print(f"📊 Total samples: {len(dataset)}")


        print("\n📋 Sample Questions from Dataset:")
        print("-"*50)
        for i, item in enumerate(dataset[:5]):
            print(f"{i+1}. {item['instruction'][:80]}...")


        categories = {}
        for item in dataset:
            inst = item['instruction'].lower()
            if 'loan' in inst:
                categories['Loan'] = categories.get('Loan', 0) + 1
            elif 'card' in inst or 'credit' in inst:
                categories['Credit Card'] = categories.get('Credit Card', 0) + 1
            elif 'account' in inst:
                categories['Account'] = categories.get('Account', 0) + 1
            elif 'insurance' in inst:
                categories['Insurance'] = categories.get('Insurance', 0) + 1
            elif 'emi' in inst or 'interest' in inst:
                categories['EMI/Interest'] = categories.get('EMI/Interest', 0) + 1

        print("\n📈 Dataset Categories:")
        for cat, count in categories.items():
            print(f"   {cat}: {count} samples")

import datetime


current_date = datetime.datetime.now().strftime("%B %Y")


loan_knowledge = f"""LOAN PRODUCTS KNOWLEDGE BASE (Updated: {current_date})

1. PERSONAL LOANS
   - Amount: ₹50,000 to ₹40 Lakhs
   - Interest Rate: 10.49% - 24% p.a.
   - Tenure: 1 to 5 years
   - Processing Fee: 1-3% + GST
   - Prepayment Charges: 0-5% (varies by bank)
   - Eligibility:
     * Salaried: 21-60 years, min ₹25,000/month
     * Self-employed: 25-65 years, min ₹3 Lakhs/year ITR
   - Documents:
     * Identity: PAN Card, Aadhaar
     * Income: 3 months salary slips, 6 months bank statement
     * Employment: Form 16, Employment letter

2. HOME LOANS
   - Amount: Up to ₹5 Crores
   - Interest Rate: 8.50% - 10.25% p.a.
   - Tenure: Up to 30 years
   - LTV Ratio: 80-90% of property value
   - Processing Fee: 0.25-1% + GST
   - Eligibility:
     * Salaried: 21-65 years, min ₹30,000/month
     * Self-employed: 25-70 years, min ₹5 Lakhs/year ITR
   - Documents:
     * Property papers: Sale deed, Allotment letter, NOC
     * Income: ITR 3 years, Bank statements 12 months
     * Identity: PAN, Aadhaar, Passport

3. CAR LOANS
   - Amount: Up to 100% of on-road price
   - Interest Rate: 8.75% - 11.50% p.a.
   - Tenure: 1 to 7 years
   - Processing Fee: 0.5-2% + GST
   - Eligibility:
     * Age: 21-65 years
     * Income: min ₹20,000/month
   - Documents:
     * Identity proof, Address proof
     * Income proof, Bank statements
     * Car quotation, Booking receipt

4. EDUCATION LOANS
   - Amount: Up to ₹1.5 Crores (abroad)
   - Interest Rate: 9.50% - 12.00% p.a.
   - Tenure: Up to 15 years (after moratorium)
   - Moratorium: Course duration + 1 year
   - Margin Money: 5-15% of loan amount
   - Collateral: Required for >₹7.5 Lakhs
   - Documents:
     * Admission letter, Fee structure
     * Co-borrower income proof
     * Academic records, Score cards

5. LOAN AGAINST PROPERTY
   - Amount: Up to 70% of property value
   - Interest Rate: 9.75% - 11.50% p.a.
   - Tenure: Up to 15 years
   - Processing Fee: 0.5-1% + GST
   - Documents:
     * Property title deed, Tax receipts
     * Income proof, Business proof
     * Valuation report, Legal opinion"""

with open('/content/bfsi_assistant/data/knowledge_base/loan_products.txt', 'w') as f:
    f.write(loan_knowledge)


rates_knowledge = f"""INTEREST RATES KNOWLEDGE BASE (Updated: {current_date})

DEPOSIT RATES:
1. SAVINGS ACCOUNT
   - Regular Savings: 2.70% - 3.50% p.a.
   - Senior Citizens: +0.50% extra
   - Daily balance interest calculation
   - Tax: Interest > ₹40,000/year taxable

2. FIXED DEPOSITS
   - 7-14 days: 3.00% - 3.50% p.a.
   - 15-30 days: 3.50% - 4.00% p.a.
   - 31-45 days: 4.00% - 4.50% p.a.
   - 46-60 days: 4.50% - 5.00% p.a.
   - 61-90 days: 5.00% - 5.50% p.a.
   - 91-180 days: 5.50% - 6.00% p.a.
   - 181 days-1 year: 6.00% - 6.50% p.a.
   - 1-2 years: 6.50% - 7.00% p.a.
   - 2-3 years: 7.00% - 7.25% p.a.
   - 3-5 years: 7.25% - 7.50% p.a.
   - 5+ years: 7.00% - 7.25% p.a.
   - Senior Citizen: +0.50% on all tenures

3. TAX-SAVER FD
   - 5-year lock-in period
   - Rate: 7.00% - 7.25% p.a.
   - 80C deduction up to ₹1.5 Lakhs
   - No premature withdrawal

4. RECURRING DEPOSITS
   - Rate: 6.50% - 7.50% p.a.
   - Tenure: 6 months to 10 years
   - Monthly deposit: ₹100 minimum

LOAN RATES:
1. HOME LOANS
   - Salaried: 8.50% - 9.75% p.a.
   - Self-employed: 9.00% - 10.25% p.a.
   - Balance Transfer: 8.50% - 9.50% p.a.
   - Top-up Loan: 9.00% - 10.00% p.a.

2. PERSONAL LOANS
   - Salaried: 10.49% - 18.00% p.a.
   - Self-employed: 12.00% - 24.00% p.a.
   - Balance Transfer: 11.00% - 16.00% p.a.

3. CAR LOANS
   - New Car: 8.75% - 10.50% p.a.
   - Used Car: 10.00% - 14.00% p.a.
   - EV Car: 8.50% - 9.50% p.a.

4. EDUCATION LOANS
   - India: 9.50% - 11.00% p.a.
   - Abroad: 10.00% - 12.00% p.a.
   - Girl Child: 0.50% concession

5. GOLD LOANS
   - Bank: 7.50% - 9.50% p.a.
   - NBFC: 9.00% - 18.00% p.a.
   - LTV: Up to 75% of gold value

6. BUSINESS LOANS
   - Secured: 10.00% - 14.00% p.a.
   - Unsecured: 14.00% - 20.00% p.a.
   - Mudra Loan: 8.00% - 12.00% p.a."""

with open('/content/bfsi_assistant/data/knowledge_base/interest_rates.txt', 'w') as f:
    f.write(rates_knowledge)


emi_knowledge = """EMI CALCULATION KNOWLEDGE BASE

EMI FORMULA:
   EMI = [P × R × (1+R)^N] / [(1+R)^N - 1]

   Where:
   P = Principal Loan Amount
   R = Monthly Interest Rate (Annual Rate ÷ 12)
   N = Number of Monthly Installments

EMI CALCULATION EXAMPLES:

1. PERSONAL LOAN EXAMPLE
   Amount: ₹5,00,000
   Rate: 12% p.a. (1% monthly)
   Tenure: 3 years (36 months)

   EMI = [5,00,000 × 0.01 × (1.01)^36] / [(1.01)^36 - 1]
   EMI = ₹16,607 per month

   Total Interest: ₹97,852
   Total Payment: ₹5,97,852

2. HOME LOAN EXAMPLE
   Amount: ₹30,00,000
   Rate: 9% p.a. (0.75% monthly)
   Tenure: 20 years (240 months)

   EMI = ₹26,992 per month

   Total Interest: ₹34,78,080
   Total Payment: ₹64,78,080

3. CAR LOAN EXAMPLE
   Amount: ₹8,00,000
   Rate: 9.5% p.a. (0.7917% monthly)
   Tenure: 5 years (60 months)

   EMI = ₹16,809 per month

   Total Interest: ₹2,08,540
   Total Payment: ₹10,08,540

4. EDUCATION LOAN EXAMPLE
   Amount: ₹15,00,000
   Rate: 10% p.a. (0.8333% monthly)
   Tenure: 10 years (120 months)
   Moratorium: 2 years (course + 1 year)

   EMI after moratorium: ₹19,814 per month

   Interest during moratorium: Simple interest
   Interest amount: ₹3,00,000 (if accrued)

EMI FACTORS:
1. Interest Rate Impact
   - 1% rate increase on ₹10L/10yrs: +₹500 EMI
   - 1% rate decrease on ₹10L/10yrs: -₹500 EMI

2. Tenure Impact
   - Longer tenure = Lower EMI, Higher interest
   - Shorter tenure = Higher EMI, Lower interest

3. Prepayment Benefits
   - Reduces principal, saves interest
   - No charges on floating rate loans
   - Part-prepayment anytime allowed

EMI TIPS:
- EMI should not exceed 40-50% of monthly income
- Use EMI calculators before applying
- Consider prepayment when you have surplus
- Check for processing fees in total cost"""

with open('/content/bfsi_assistant/data/knowledge_base/emi_calculations.txt', 'w') as f:
    f.write(emi_knowledge)

print("✅ Comprehensive Knowledge Base Created!")
print("📚 Files created:")
print("   - loan_products.txt (Loan information)")
print("   - interest_rates.txt (Interest rate details)")
print("   - emi_calculations.txt (EMI formulas and examples)")

config_content = []
config_content.append("model:")
config_content.append("  base_model: \"microsoft/phi-2\"")
config_content.append("  fine_tuned_path: \"/content/bfsi_assistant/models/fine_tuned_slm\"")
config_content.append("  embedding_model: \"sentence-transformers/all-MiniLM-L6-v2\"")
config_content.append("")
config_content.append("rag:")
config_content.append("  knowledge_base_path: \"/content/bfsi_assistant/data/knowledge_base/\"")
config_content.append("  chunk_size: 500")
config_content.append("  top_k: 5")
config_content.append("  embedding_cache: \"/content/bfsi_assistant/data/embeddings/\"")
config_content.append("")
config_content.append("dataset:")
config_content.append("  path: \"/content/bfsi_assistant/data/alpaca_dataset.json\"")
config_content.append("  similarity_threshold: 0.80")
config_content.append("")
config_content.append("guardrails:")
config_content.append("  blocked_terms: [\"fake\", \"illegal\", \"hack\", \"steal\", \"fraud\", \"scam\"]")
config_content.append("  max_response_length: 1000")
config_content.append("")
config_content.append("assistant:")
config_content.append("  name: \"BFSI Assistant\"")
config_content.append("  version: \"2.0\"")
config_content.append("  welcome_message: \"Welcome to BFSI Assistant! How can I help you with banking, loans, or insurance today?\"")

with open('/content/bfsi_assistant/config.yaml', 'w') as f:
    f.write("\n".join(config_content))

print("✅ Configuration file created!")

rag_code = []
rag_code.append("import os")
rag_code.append("import numpy as np")
rag_code.append("from sentence_transformers import SentenceTransformer")
rag_code.append("from sklearn.metrics.pairwise import cosine_similarity")
rag_code.append("import hashlib")
rag_code.append("")
rag_code.append("class RAGEngine:")
rag_code.append("    def __init__(self, config):")
rag_code.append("        self.config = config")
rag_code.append("        self.embedder = SentenceTransformer(config[\"model\"][\"embedding_model\"])")
rag_code.append("        self.knowledge_base = []")
rag_code.append("        self.embeddings = None")
rag_code.append("")
rag_code.append("    def load_knowledge_base(self):")
rag_code.append("        \"\"\"Load and index all knowledge documents\"\"\"")
rag_code.append("        documents = []")
rag_code.append("        kb_path = self.config[\"rag\"][\"knowledge_base_path\"]")
rag_code.append("        ")
rag_code.append("        if not os.path.exists(kb_path):")
rag_code.append("            print(\"⚠️ Knowledge base path not found\")")
rag_code.append("            return []")
rag_code.append("")
rag_code.append("        print(\"📚 Loading knowledge base...\")")
rag_code.append("        for filename in os.listdir(kb_path):")
rag_code.append("            if filename.endswith(\".txt\"):")
rag_code.append("                filepath = os.path.join(kb_path, filename)")
rag_code.append("                try:")
rag_code.append("                    with open(filepath, \"r\", encoding=\"utf-8\") as f:")
rag_code.append("                        content = f.read()")
rag_code.append("                    ")
rag_code.append("                    chunks = self._chunk_text(content)")
rag_code.append("                    ")
rag_code.append("                    for i, chunk in enumerate(chunks):")
rag_code.append("                        if chunk.strip():")
rag_code.append("                            doc_id = hashlib.md5(f\"{filename}_{i}\".encode()).hexdigest()")
rag_code.append("                            documents.append({")
rag_code.append("                                \"id\": doc_id,")
rag_code.append("                                \"content\": chunk,")
rag_code.append("                                \"source\": filename.replace(\".txt\", \"\").replace(\"_\", \" \").title(),")
rag_code.append("                                \"category\": self._get_category(filename)")
rag_code.append("                            })")
rag_code.append("                except Exception as e:")
rag_code.append("                    print(f\"⚠️ Error reading {filename}: {e}\")")
rag_code.append("")
rag_code.append("        self.knowledge_base = documents")
rag_code.append("        if documents:")
rag_code.append("            texts = [doc[\"content\"] for doc in documents]")
rag_code.append("            self.embeddings = self.embedder.encode(texts)")
rag_code.append("            print(f\"✅ Loaded {len(documents)} knowledge chunks\")")
rag_code.append("        else:")
rag_code.append("            print(\"⚠️ No documents loaded\")")
rag_code.append("        ")
rag_code.append("        return documents")
rag_code.append("")
rag_code.append("    def _get_category(self, filename):")
rag_code.append("        if \"loan\" in filename.lower():")
rag_code.append("            return \"Loans\"")
rag_code.append("        elif \"interest\" in filename.lower():")
rag_code.append("            return \"Interest Rates\"")
rag_code.append("        elif \"emi\" in filename.lower():")
rag_code.append("            return \"EMI Calculations\"")
rag_code.append("        else:")
rag_code.append("            return \"General\"")
rag_code.append("")
rag_code.append("    def _chunk_text(self, text, chunk_size=500):")
rag_code.append("        words = text.split()")
rag_code.append("        chunks = []")
rag_code.append("        for i in range(0, len(words), chunk_size):")
rag_code.append("            chunk = \" \".join(words[i:i+chunk_size])")
rag_code.append("            if chunk.strip():")
rag_code.append("                chunks.append(chunk)")
rag_code.append("        return chunks")
rag_code.append("")
rag_code.append("    def retrieve(self, query, top_k=5, category_filter=None):")
rag_code.append("        if not self.knowledge_base:")
rag_code.append("            self.load_knowledge_base()")
rag_code.append("            ")
rag_code.append("        if not self.knowledge_base or self.embeddings is None:")
rag_code.append("            return []")
rag_code.append("")
rag_code.append("        query_embedding = self.embedder.encode([query])")
rag_code.append("        similarities = cosine_similarity(query_embedding, self.embeddings)[0]")
rag_code.append("        top_indices = np.argsort(similarities)[-top_k:][::-1]")
rag_code.append("")
rag_code.append("        results = []")
rag_code.append("        for idx in top_indices:")
rag_code.append("            doc = self.knowledge_base[idx]")
rag_code.append("            if category_filter and doc[\"category\"] != category_filter:")
rag_code.append("                continue")
rag_code.append("            results.append({")
rag_code.append("                \"content\": doc[\"content\"],")
rag_code.append("                \"source\": doc[\"source\"],")
rag_code.append("                \"category\": doc[\"category\"],")
rag_code.append("                \"relevance\": float(similarities[idx]),")
rag_code.append("                \"id\": doc[\"id\"]")
rag_code.append("            })")
rag_code.append("        ")
rag_code.append("        return results")
rag_code.append("")
rag_code.append("    def generate_response(self, query, retrieved_docs):")
rag_code.append("        if not retrieved_docs:")
rag_code.append("            return \"No relevant information found.\"")
rag_code.append("")
rag_code.append("        # Group by category")
rag_code.append("        grouped = {}")
rag_code.append("        for doc in retrieved_docs:")
rag_code.append("            cat = doc[\"category\"]")
rag_code.append("            if cat not in grouped:")
rag_code.append("                grouped[cat] = []")
rag_code.append("            grouped[cat].append(doc)")
rag_code.append("")
rag_code.append("        # Build response")
rag_code.append("        response_parts = []")
rag_code.append("        response_parts.append(\"📌 Here's what I found:\")")
rag_code.append("        response_parts.append(\"\")")
rag_code.append("")
rag_code.append("        for category, docs in grouped.items():")
rag_code.append("            response_parts.append(f\"🔹 {category}:\")")
rag_code.append("            for doc in docs[:2]:  # Fixed: Removed extra parenthesis")
rag_code.append("                sentences = doc[\"content\"].split(\". \")")
rag_code.append("                summary = \". \".join(sentences[:2]) + \".\"")
rag_code.append("                response_parts.append(f\"   • {summary}\")")
rag_code.append("            response_parts.append(\"\")")
rag_code.append("")
rag_code.append("        response_parts.append(\"💡 Note: These are general guidelines. Please verify with your bank for exact terms.\")")
rag_code.append("        ")
rag_code.append("        return \"\\n\".join(response_parts)")

rag_code_final = "\n".join(rag_code)

with open('/content/bfsi_assistant/src/rag_engine.py', 'w') as f:
    f.write(rag_code_final)
print("✅ RAG Engine created")



response_code = []
response_code.append("import json")
response_code.append("import numpy as np")
response_code.append("from sentence_transformers import SentenceTransformer")
response_code.append("from sklearn.metrics.pairwise import cosine_similarity")
response_code.append("import re")
response_code.append("")
response_code.append("class ResponseLogic:")
response_code.append("    def __init__(self, config, rag_engine):")
response_code.append("        self.config = config")
response_code.append("        self.rag_engine = rag_engine")
response_code.append("        self.conversation_history = []")
response_code.append("")
response_code.append("        # Load dataset")
response_code.append("        try:")
response_code.append("            with open(config[\"dataset\"][\"path\"], \"r\", encoding=\"utf-8\") as f:")
response_code.append("                self.dataset = json.load(f)")
response_code.append("            print(f\"✅ Loaded {len(self.dataset)} training samples\")")
response_code.append("        except Exception as e:")
response_code.append("            print(f\"⚠️ Could not load dataset: {e}\")")
response_code.append("            self.dataset = []")
response_code.append("")
response_code.append("        # Load embedding model")
response_code.append("        self.embedder = SentenceTransformer(config[\"model\"][\"embedding_model\"])")
response_code.append("")
response_code.append("        # Create dataset embeddings if available")
response_code.append("        if self.dataset:")
response_code.append("            texts = []")
response_code.append("            for item in self.dataset:")
response_code.append("                text = f\"{item['instruction']} {item['input']}\".strip()")
response_code.append("                texts.append(text)")
response_code.append("            self.dataset_embeddings = self.embedder.encode(texts)")
response_code.append("        else:")
response_code.append("            self.dataset_embeddings = np.array([])")
response_code.append("")
response_code.append("        self.threshold = config[\"dataset\"][\"similarity_threshold\"]")
response_code.append("")
response_code.append("    def detect_query_type(self, query):")
response_code.append("        \"\"\"Detect the type of query for better routing\"\"\"")
response_code.append("        query_lower = query.lower()")
response_code.append("        ")
response_code.append("        # Loan-related queries")
response_code.append("        if any(word in query_lower for word in [\"loan\", \"borrow\", \"lend\"]):")
response_code.append("            if any(word in query_lower for word in [\"eligibility\", \"eligible\", \"can i get\"]):")
response_code.append("                return \"loan_eligibility\"")
response_code.append("            elif any(word in query_lower for word in [\"interest\", \"rate\"]):")
response_code.append("                return \"loan_interest\"")
response_code.append("            elif any(word in query_lower for word in [\"document\", \"require\", \"need\"]):")
response_code.append("                return \"loan_documents\"")
response_code.append("            else:")
response_code.append("                return \"loan_general\"")
response_code.append("        ")
response_code.append("        # EMI/Calculation queries")
response_code.append("        elif any(word in query_lower for word in [\"emi\", \"calculate\", \"computation\", \"formula\"]):")
response_code.append("            return \"emi_calculation\"")
response_code.append("        ")
response_code.append("        # Interest rate queries")
response_code.append("        elif any(word in query_lower for word in [\"interest rate\", \"fd rate\", \"savings rate\"]):")
response_code.append("            return \"interest_rates\"")
response_code.append("        ")
response_code.append("        # Account queries")
response_code.append("        elif any(word in query_lower for word in [\"account\", \"balance\", \"statement\", \"passbook\"]):")
response_code.append("            return \"account_services\"")
response_code.append("        ")
response_code.append("        # Card queries")
response_code.append("        elif any(word in query_lower for word in [\"card\", \"credit\", \"debit\"]):")
response_code.append("            return \"card_services\"")
response_code.append("        ")
response_code.append("        # Insurance queries")
response_code.append("        elif any(word in query_lower for word in [\"insurance\", \"claim\", \"policy\"]):")
response_code.append("            return \"insurance\"")
response_code.append("        ")
response_code.append("        # Default")
response_code.append("        return \"general\"")
response_code.append("")
response_code.append("    def extract_parameters(self, query, input_context):")
response_code.append("        \"\"\"Extract numerical parameters from query\"\"\"")
response_code.append("        params = {}")
response_code.append("        full_text = query + \" \" + input_context")
response_code.append("        ")
response_code.append("        # Extract amount (₹ pattern)")
response_code.append("        amount_pattern = r'[₹]?\\s*(\\d+(?:[\\,\\.]\\d+)?)\\s*(?:lakhs?|crores?|k|thousand)?'")
response_code.append("        amounts = re.findall(amount_pattern, full_text, re.IGNORECASE)")
response_code.append("        if amounts:")
response_code.append("            try:")
response_code.append("                params[\"amount\"] = float(amounts[0].replace(\",\", \"\"))")
response_code.append("            except:")
response_code.append("                pass")
response_code.append("        ")
response_code.append("        # Extract percentage")
response_code.append("        percent_pattern = r'(\\d+(?:\\.\\d+)?)\\s*%'")
response_code.append("        percentages = re.findall(percent_pattern, full_text)")
response_code.append("        if percentages:")
response_code.append("            params[\"rate\"] = float(percentages[0])")
response_code.append("        ")
response_code.append("        # Extract years/months")
response_code.append("        year_pattern = r'(\\d+)\\s*(?:years?|yrs?)'")
response_code.append("        years = re.findall(year_pattern, full_text, re.IGNORECASE)")
response_code.append("        if years:")
response_code.append("            params[\"years\"] = int(years[0])")
response_code.append("        ")
response_code.append("        return params")
response_code.append("")
response_code.append("    def process_query(self, query, input_context=\"\"):")
response_code.append("        \"\"\"Process query with enhanced interaction\"\"\"")
response_code.append("        ")
response_code.append("        # Add to history")
response_code.append("        self.conversation_history.append({\"role\": \"user\", \"content\": query})")
response_code.append("")
response_code.append("        # Detect query type")
response_code.append("        query_type = self.detect_query_type(query)")
response_code.append("        ")
response_code.append("        # Extract parameters")
response_code.append("        params = self.extract_parameters(query, input_context)")
response_code.append("")
response_code.append("        # Try dataset match first")
response_code.append("        if len(self.dataset_embeddings) > 0:")
response_code.append("            match = self._find_dataset_match(query, input_context)")
response_code.append("            if match:")
response_code.append("                response = match[\"response\"]")
response_code.append("                source = \"📚 Dataset\"")
response_code.append("                self.conversation_history.append({\"role\": \"assistant\", \"content\": response})")
response_code.append("                return response, source, query_type, params")
response_code.append("")
response_code.append("        # For calculations, use RAG with specific category")
response_code.append("        if query_type == \"emi_calculation\" and params:")
response_code.append("            rag_response = self._get_calculated_response(query, params)")
response_code.append("            if rag_response:")
response_code.append("                self.conversation_history.append({\"role\": \"assistant\", \"content\": rag_response})")
response_code.append("                return rag_response, \"🧮 Calculator\", query_type, params")
response_code.append("")
response_code.append("        # Use RAG for other queries")
response_code.append("        category_map = {")
response_code.append("            \"loan_eligibility\": \"Loans\",")
response_code.append("            \"loan_interest\": \"Interest Rates\",")
response_code.append("            \"loan_documents\": \"Loans\",")
response_code.append("            \"interest_rates\": \"Interest Rates\",")
response_code.append("            \"emi_calculation\": \"EMI Calculations\"")
response_code.append("        }")
response_code.append("        ")
response_code.append("        category = category_map.get(query_type)")
response_code.append("        retrieved = self.rag_engine.retrieve(query, top_k=5, category_filter=category)")
response_code.append("        ")
response_code.append("        if retrieved:")
response_code.append("            response = self.rag_engine.generate_response(query, retrieved)")
response_code.append("            source = f\"🔍 Knowledge Base ({retrieved[0]['source']})\"")
response_code.append("        else:")
response_code.append("            response = self._get_fallback_response(query_type)")
response_code.append("            source = \"ℹ️ General Information\"")
response_code.append("")
response_code.append("        self.conversation_history.append({\"role\": \"assistant\", \"content\": response})")
response_code.append("        return response, source, query_type, params")
response_code.append("")
response_code.append("    def _find_dataset_match(self, query, input_context):")
response_code.append("        \"\"\"Find best matching dataset entry\"\"\"")
response_code.append("        if len(self.dataset_embeddings) == 0:")
response_code.append("            return None")
response_code.append("")
response_code.append("        query_text = f\"{query} {input_context}\".strip()")
response_code.append("        if not query_text:")
response_code.append("            query_text = query")
response_code.append("")
response_code.append("        query_embedding = self.embedder.encode([query_text])")
response_code.append("        similarities = cosine_similarity(query_embedding, self.dataset_embeddings)[0]")
response_code.append("        ")
response_code.append("        best_idx = np.argmax(similarities)")
response_code.append("        best_score = similarities[best_idx]")
response_code.append("")
response_code.append("        if best_score >= self.threshold:")
response_code.append("            return {")
response_code.append("                \"response\": self.dataset[best_idx][\"output\"],")
response_code.append("                \"score\": float(best_score)")
response_code.append("            }")
response_code.append("        return None")
response_code.append("")
response_code.append("    def _get_calculated_response(self, query, params):")
response_code.append("        \"\"\"Generate calculated response for EMI queries\"\"\"")
response_code.append("        if \"amount\" in params and \"rate\" in params and \"years\" in params:")
response_code.append("            P = params[\"amount\"] * 100000 if params[\"amount\"] < 100 else params[\"amount\"]  # Handle lakhs")
response_code.append("            R = params[\"rate\"] / 12 / 100")
response_code.append("            N = params[\"years\"] * 12")
response_code.append("            ")
response_code.append("            EMI = P * R * ((1+R)**N) / (((1+R)**N) - 1)")
response_code.append("            total = EMI * N")
response_code.append("            interest = total - P")
response_code.append("            ")
response_code.append("            response = f\"📊 EMI Calculation Result:\\n\\n\"")
response_code.append("            response += f\"Loan Amount: ₹{P:,.0f}\\n\"")
response_code.append("            response += f\"Interest Rate: {params['rate']}% p.a.\\n\"")
response_code.append("            response += f\"Tenure: {params['years']} years\\n\"")
response_code.append("            response += f\"Monthly EMI: ₹{EMI:,.0f}\\n\"")
response_code.append("            response += f\"Total Interest: ₹{interest:,.0f}\\n\"")
response_code.append("            response += f\"Total Payment: ₹{total:,.0f}\\n\\n\"")
response_code.append("            response += \"Note: This is an approximate calculation. Actual EMI may vary based on processing fees and other charges.\"")
response_code.append("            return response")
response_code.append("        return None")
response_code.append("")
response_code.append("    def _get_fallback_response(self, query_type):")
response_code.append("        \"\"\"Get fallback response based on query type\"\"\"")
response_code.append("        fallbacks = {")
response_code.append("            \"loan_eligibility\": \"To check loan eligibility, we typically need your income, existing obligations, and credit score. Please provide these details for a personalized assessment.\",")
response_code.append("            \"loan_interest\": \"Interest rates vary based on loan type, amount, tenure, and your credit profile. Please specify which loan you're interested in (personal, home, car, etc.) for accurate rates.\",")
response_code.append("            \"emi_calculation\": \"To calculate EMI, please provide the loan amount, interest rate, and tenure. For example: 'Calculate EMI for ₹10 Lakhs at 9% for 5 years'.\",")
response_code.append("            \"general\": \"I'm here to help with banking, loans, investments, and insurance queries. Could you please provide more details about what you'd like to know?\"")
response_code.append("        }")
response_code.append("        return fallbacks.get(query_type, fallbacks[\"general\"])")

response_code_final = "\n".join(response_code)

with open('/content/bfsi_assistant/src/response_logic.py', 'w') as f:
    f.write(response_code_final)
print("✅ Interactive Response Logic created!")

guardrails_code = []
guardrails_code.append("import re")
guardrails_code.append("")
guardrails_code.append("class Guardrails:")
guardrails_code.append("    def __init__(self, config):")
guardrails_code.append("        self.config = config")
guardrails_code.append("        self.blocked_terms = config[\"guardrails\"][\"blocked_terms\"]")
guardrails_code.append("        self.bfsi_keywords = [")
guardrails_code.append("            \"loan\", \"bank\", \"insurance\", \"account\", \"credit\", \"debit\",")
guardrails_code.append("            \"emi\", \"interest\", \"investment\", \"mutual fund\", \"stock\",")
guardrails_code.append("            \"fd\", \"rd\", \"ppf\", \"nps\", \"tax\", \"cibil\", \"score\",")
guardrails_code.append("            \"savings\", \"current\", \"salary\", \"fixed deposit\", \"recurring deposit\"")
guardrails_code.append("        ]")
guardrails_code.append("")
guardrails_code.append("    def validate_query(self, query):")
guardrails_code.append("        \"\"\"Validate and sanitize incoming query\"\"\"")
guardrails_code.append("        if not query or len(query.strip()) < 3:")
guardrails_code.append("            return False, \"Please ask a valid question.\"")
guardrails_code.append("")
guardrails_code.append("        query_lower = query.lower()")
guardrails_code.append("        ")
guardrails_code.append("        # Check for blocked terms")
guardrails_code.append("        for term in self.blocked_terms:")
guardrails_code.append("            if term in query_lower:")
guardrails_code.append("                return False, f\"I cannot process queries containing '{term}'.\"")
guardrails_code.append("")
guardrails_code.append("        # Check if BFSI related")
guardrails_code.append("        if not any(keyword in query_lower for keyword in self.bfsi_keywords):")
guardrails_code.append("            return False, \"I specialize in banking and financial queries. Could you please ask something related to banking, loans, or investments?\"")
guardrails_code.append("")
guardrails_code.append("        return True, \"\"")
guardrails_code.append("")
guardrails_code.append("    def sanitize_response(self, response):")
guardrails_code.append("        \"\"\"Add appropriate disclaimers\"\"\"")
guardrails_code.append("        disclaimer = \"\\n\\n---\\n*Disclaimer: This information is for general guidance only. Please verify with your bank for exact terms and conditions.*\"")
guardrails_code.append("        return response + disclaimer")

guardrails_code_final = "\n".join(guardrails_code)

with open('/content/bfsi_assistant/src/guardrails.py', 'w') as f:
    f.write(guardrails_code_final)
print("✅ Guardrails created!")

main_code = []
main_code.append("import yaml")
main_code.append("import sys")
main_code.append("import os")
main_code.append("")
main_code.append("sys.path.append(\"/content/bfsi_assistant/src\")")
main_code.append("")
main_code.append("try:")
main_code.append("    from rag_engine import RAGEngine")
main_code.append("    from response_logic import ResponseLogic")
main_code.append("    from guardrails import Guardrails")
main_code.append("except ImportError as e:")
main_code.append("    print(f\"Import error: {e}\")")
main_code.append("")
main_code.append("class BFSIAssistant:")
main_code.append("    def __init__(self, config_path):")
main_code.append("        with open(config_path, \"r\") as f:")
main_code.append("            self.config = yaml.safe_load(f)")
main_code.append("")
main_code.append("        print(\"🚀 Initializing BFSI Assistant...\")")
main_code.append("        self.rag_engine = RAGEngine(self.config)")
main_code.append("        self.response_logic = ResponseLogic(self.config, self.rag_engine)")
main_code.append("        self.guardrails = Guardrails(self.config)")
main_code.append("")
main_code.append("        # Load knowledge base")
main_code.append("        self.rag_engine.load_knowledge_base()")
main_code.append("        print(\"✅ BFSI Assistant ready!\")")
main_code.append("")
main_code.append("    def process_query(self, instruction, input_text=\"\"):")
main_code.append("        \"\"\"Process a single query and return response with metadata\"\"\"")
main_code.append("        try:")
main_code.append("            # Validate query")
main_code.append("            valid, message = self.guardrails.validate_query(instruction)")
main_code.append("            if not valid:")
main_code.append("                return {")
main_code.append("                    \"response\": message,")
main_code.append("                    \"source\": \"⚠️ Guardrail\",")
main_code.append("                    \"type\": \"blocked\",")
main_code.append("                    \"params\": {}")
main_code.append("                }")
main_code.append("")
main_code.append("            # Get response from logic layer")
main_code.append("            response, source, query_type, params = self.response_logic.process_query(instruction, input_text)")
main_code.append("")
main_code.append("            # Sanitize response")
main_code.append("            response = self.guardrails.sanitize_response(response)")
main_code.append("")
main_code.append("            return {")
main_code.append("                \"response\": response,")
main_code.append("                \"source\": source,")
main_code.append("                \"type\": query_type,")
main_code.append("                \"params\": params")
main_code.append("            }")
main_code.append("        except Exception as e:")
main_code.append("            return {")
main_code.append("                \"response\": f\"I encountered an error: {str(e)}. Please try again with a different question.\",")
main_code.append("                \"source\": \"❌ Error\",")
main_code.append("                \"type\": \"error\",")
main_code.append("                \"params\": {}")
main_code.append("            }")
main_code.append("")
main_code.append("    def chat(self):")
main_code.append("        \"\"\"Interactive command-line chat mode\"\"\"")
main_code.append("        print(\"\\n\" + \"=\"*60)")
main_code.append("        print(self.config[\"assistant\"][\"welcome_message\"])")
main_code.append("        print(\"=\"*60)")
main_code.append("        print(\"Commands: 'quit' to exit, 'clear' to clear screen\\n\")")
main_code.append("")
main_code.append("        while True:")
main_code.append("            try:")
main_code.append("                # Get user input")
main_code.append("                print(\"\\n\" + \"-\"*60)")
main_code.append("                instruction = input(\"👤 You: \").strip()")
main_code.append("                ")
main_code.append("                if instruction.lower() in [\"quit\", \"exit\", \"bye\"]:")
main_code.append("                    print(\"\\n👋 Thank you for using BFSI Assistant. Goodbye!\")")
main_code.append("                    break")
main_code.append("                ")
main_code.append("                if instruction.lower() == \"clear\":")
main_code.append("                    os.system(\"clear\" if os.name == \"posix\" else \"cls\")")
main_code.append("                    continue")
main_code.append("")
main_code.append("                if not instruction:")
main_code.append("                    continue")
main_code.append("")
main_code.append("                # Get optional context")
main_code.append("                print(\"📝 Additional context (optional, press Enter to skip):\")")
main_code.append("                input_text = input().strip()")
main_code.append("")
main_code.append("                # Process query")
main_code.append("                print(\"\\n🤖 Assistant: \", end=\"\", flush=True)")
main_code.append("                result = self.process_query(instruction, input_text)")
main_code.append("                ")
main_code.append("                # Display response")
main_code.append("                print(result[\"response\"])")
main_code.append("                print(f\"\\n[{result['source']}] | Type: {result['type']}\")")
main_code.append("                ")
main_code.append("                if result[\"params\"]:")
main_code.append("                    print(f\"📊 Detected parameters: {result['params']}\")")
main_code.append("")
main_code.append("            except KeyboardInterrupt:")
main_code.append("                print(\"\\n\\n👋 Goodbye!\")")
main_code.append("                break")
main_code.append("            except Exception as e:")
main_code.append("                print(f\"\\n⚠️ Error: {e}\")")

main_code_final = "\n".join(main_code)

with open('/content/bfsi_assistant/src/main.py', 'w') as f:
    f.write(main_code_final)
print("✅ Main Assistant created!")

import sys
sys.path.append('/content/bfsi_assistant')
import yaml

print("🧪 Testing BFSI Assistant Components...")
print("="*50)

try:

    from src.rag_engine import RAGEngine
    print("✅ RAG Engine - OK")

    from src.guardrails import Guardrails
    print("✅ Guardrails - OK")

    from src.response_logic import ResponseLogic
    print("✅ Response Logic - OK")

    from src.main import BFSIAssistant
    print("✅ Main Assistant - OK")


    print("\n🚀 Initializing assistant...")
    assistant = BFSIAssistant('/content/bfsi_assistant/config.yaml')


    print("\n📝 Testing sample queries...")
    test_queries = [
        ("What is a home loan?", ""),
        ("Calculate EMI", "Amount: ₹10 Lakhs, rate: 9%, years: 5"),
    ]

    for query, context in test_queries:
        print(f"\nQ: {query}")
        if context:
            print(f"Context: {context}")
        result = assistant.process_query(query, context)
        print(f"Response: {result['response'][:100]}...")
        print(f"Source: {result['source']}")

    print("\n🎉 All tests passed! Assistant is ready to use!")

except Exception as e:
    print(f"❌ Test failed: {e}")

!pip install -q gradio plotly

import gradio as gr
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
import sys
sys.path.append('/content/bfsi_assistant')
from src.main import BFSIAssistant
import yaml
import datetime


assistant = BFSIAssistant('/content/bfsi_assistant/config.yaml')


sample_questions = [
    "What is my loan eligibility?",
    "Calculate EMI for home loan",
    "What are current FD rates?",
    "Documents needed for personal loan",
    "How to apply for credit card?",
    "Explain tax benefits on home loan",
    "What is CIBIL score?",
    "Compare fixed vs floating rate",
    "Gold loan interest rates",
    "PPF account benefits"
]

def get_emi_chart(amount, rate, years):
    """Generate EMI chart"""
    P = amount * 100000 if amount < 100 else amount
    r = rate / 12 / 100
    n = years * 12

    emi = P * r * ((1+r)**n) / (((1+r)**n) - 1)


    total_payment = emi * n
    total_interest = total_payment - P

    fig = go.Figure(data=[go.Pie(
        labels=['Principal', 'Interest'],
        values=[P, total_interest],
        hole=.3,
        marker_colors=['#2E86AB', '#A23B72']
    )])

    fig.update_layout(
        title_text=f'Loan Breakdown (EMI: ₹{emi:,.0f}/month)',
        showlegend=True,
        height=400
    )

    return fig

def format_response(response, source, query_type, params):
    """Format response with styling"""
    formatted = f"{response}\n\n"
    formatted += f"---\n"
    formatted += f"*Source: {source}*"
    if params:
        formatted += f"\n*Parameters detected: {params}*"
    return formatted

def respond(question, details, history):
    """Main response function"""
    if not question:
        return history, history, "", ""


    result = assistant.process_query(question, details)


    bot_message = format_response(
        result["response"],
        result["source"],
        result["type"],
        result["params"]
    )


    history = history or []
    history.append((question, bot_message))


    chart = None
    if result["type"] == "emi_calculation" and result["params"]:
        params = result["params"]
        if "amount" in params and "rate" in params and "years" in params:
            chart = get_emi_chart(params["amount"], params["rate"], params["years"])

    return history, history, "", "", chart

def clear_history():
    """Clear chat history"""
    return [], None


with gr.Blocks(theme=gr.themes.Soft(), title="BFSI Call Center AI Assistant") as demo:
    gr.Markdown("""
    # 🏦 BFSI Call Center AI Assistant
    ### Your 24/7 Banking, Financial, and Insurance Assistant

    Ask me anything about:
    - 💰 **Loans** (Personal, Home, Car, Education)
    - 📊 **Interest Rates** (FD, RD, Savings)
    - 🧮 **EMI Calculations**
    - 💳 **Credit/Debit Cards**
    - 📋 **Account Services**
    - 🛡️ **Insurance**
    """)

    with gr.Row():
        with gr.Column(scale=2):

            chatbot = gr.Chatbot(label="Conversation", height=500)

            with gr.Row():
                msg = gr.Textbox(
                    label="Your Question",
                    placeholder="Type your question here...",
                    scale=4
                )
                details = gr.Textbox(
                    label="Additional Details",
                    placeholder="e.g., Income: ₹50,000, Loan amount: ₹10 Lakhs",
                    scale=3
                )

            with gr.Row():
                submit_btn = gr.Button("🚀 Send", variant="primary", scale=1)
                clear_btn = gr.Button("🗑️ Clear Chat", scale=1)

        with gr.Column(scale=1):

            gr.Markdown("### 📌 Quick Questions")
            quick_btns = []
            for q in sample_questions[:5]:
                btn = gr.Button(q, size="sm")
                quick_btns.append(btn)

            gr.Markdown("### 📈 EMI Visualizer")
            chart = gr.Plot(label="Loan Breakdown")

            gr.Markdown("### ℹ️ Tips")
            gr.Markdown("""
            - Be specific with numbers
            - Mention loan type
            - Include tenure for EMI
            - Ask about documents
            """)


    def respond_wrapper(question, details, history):
        return respond(question, details, history)

    submit_btn.click(
        respond_wrapper,
        [msg, details, chatbot],
        [chatbot, chatbot, msg, details, chart]
    )

    msg.submit(
        respond_wrapper,
        [msg, details, chatbot],
        [chatbot, chatbot, msg, details, chart]
    )

    clear_btn.click(
        clear_history,
        None,
        [chatbot, chart]
    )


    for btn in quick_btns:
        btn.click(
            lambda q=btn.value: (q, "", None),
            None,
            [msg, details, chatbot]
        )

    gr.Markdown("""
    ---
    *Disclaimer: This AI assistant provides general guidance. Please verify all information with your bank.*
    """)


print("🚀 Starting Interactive Web Interface...")
print("📱 Click the URL below to open the assistant")
demo.launch(share=True, debug=False)

